# Generated by Django 3.1.2 on 2021-10-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('price_open', models.FloatField()),
                ('price_high', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_close', models.FloatField()),
                ('volume_traded', models.FloatField()),
                ('trades_count', models.IntegerField()),
                ('ticker', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ethereum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('price_open', models.FloatField()),
                ('price_high', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_close', models.FloatField()),
                ('volume_traded', models.FloatField()),
                ('trades_count', models.IntegerField()),
                ('ticker', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
                ('name', models.FloatField()),
                ('current_price', models.FloatField()),
                ('high24', models.FloatField()),
                ('low24', models.FloatField()),
                ('volume', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('supply', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='coin_count',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coin_list',
            field=models.CharField(choices=[('AAVE', 'Aave'), ('ADA', 'Cardano'), ('ANT', 'Aragon'), ('ATOM', 'Cosmos'), ('BAL', 'Balancer'), ('BTC', 'Bitcoin'), ('CQT', 'Covalent'), ('ETC', 'Ethereum Classic'), ('ETH', 'Ethereum'), ('KAR', 'Karura'), ('USDT', 'Tether'), ('XRP', 'Ripple')], default=[], max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
