# Generated by Django 3.1.2 on 2021-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
                ('name', models.FloatField()),
                ('current_price', models.FloatField()),
                ('high24', models.FloatField()),
                ('low24', models.FloatField()),
                ('volume', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('supply', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='coin_count',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coin_list',
            field=models.CharField(default=[], max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
