# Generated by Django 3.1.2 on 2021-10-11 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandbox', '0003_auto_20211010_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='coin_list',
            field=models.CharField(choices=[('AAVE', 'Aave'), ('ANT', 'Aragon'), ('REP', 'Augur'), ('BAL', 'Balancer'), ('BTC', 'Bitcoin'), ('ADA', 'Cardano'), ('ATOM', 'Cosmos'), ('ETH', 'Ethereum'), ('ETC', 'EthereumClassic'), ('OXT', 'Orchid'), ('USDT', 'Tether'), ('XTZ', 'Tezos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='investment',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
