# Generated by Django 3.1.2 on 2021-10-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0007_auto_20211011_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
