# Generated by Django 3.1.2 on 2021-10-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0008_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='investment',
            field=models.FloatField(),
        ),
    ]
