# Generated by Django 3.1.2 on 2021-10-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandbox', '0009_auto_20211012_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='aave',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aave',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aragon',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aragon',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='augur',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='augur',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancer',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='balancer',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardano',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardano',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cosmos',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cosmos',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ethereum',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ethereum',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ethereumclassic',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ethereumclassic',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orchid',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orchid',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tether',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tether',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tezos',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tezos',
            name='owner',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
