# Generated by Django 3.1.2 on 2021-10-12 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0010_auto_20211012_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aave',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='aragon',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='augur',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='balancer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bitcoin',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cardano',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cosmos',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ethereum',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ethereumclassic',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='orchid',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tether',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tezos',
            name='owner',
        ),
        migrations.AddField(
            model_name='aave',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='aragon',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='augur',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='balancer',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='cardano',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='cosmos',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='ethereum',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='ethereumclassic',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='orchid',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='tether',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AddField(
            model_name='tezos',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='coin_list',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
