# Generated by Django 3.1.2 on 2021-10-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0011_auto_20211012_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aave',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='aragon',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='augur',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='balancer',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='cardano',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='cosmos',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='ethereum',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='ethereumclassic',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='tether',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
        migrations.AlterField(
            model_name='tezos',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.portfolio'),
        ),
    ]
