# Generated by Django 3.1.2 on 2021-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0012_auto_20211012_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
