# Generated by Django 3.1.2 on 2021-10-13 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0014_auto_20211012_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
