# Generated by Django 3.2.8 on 2021-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0016_transaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
