# Generated by Django 3.2.8 on 2021-10-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0017_transaction_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='balance',
            new_name='portfolio_balance',
        ),
    ]
