# Generated by Django 3.2.8 on 2021-10-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0018_rename_balance_transaction_portfolio_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ds', models.FloatField(default=float("nan"))),
                ('yhat', models.FloatField(default=float("nan"))),
                ('yhat_upper', models.FloatField(default=float("nan"))),
                ('yhat_lower', models.FloatField(default=float("nan"))),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox.coin')),
            ],
        ),
    ]
