# Generated by Django 3.2.8 on 2021-10-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0019_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='ds',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='yhat',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='yhat_lower',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='yhat_upper',
            field=models.FloatField(default=float("nan")),
        ),
    ]
