# Generated by Django 3.2.8 on 2021-10-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0020_auto_20211016_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='yhat',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='yhat_lower',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='yhat_upper',
            field=models.FloatField(default=float("nan")),
        ),
    ]
